# Production Vs Stoppage:(linear regression)


**SUPERVISED LEARNING:**:

In [1]:
import pandas as pd
import pickle
import os
import xlrd
import openpyxl 
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib
matplotlib.rcParams["figure.figsize"]=(20,10)
from sklearn import linear_model


In [2]:
df12=pd.read_excel(
     os.path.join("C:\\Users\\Athul krishna\\myexcels\\","production\\", 'product12.xml.xlsx'),
     engine='openpyxl',
)
df13=pd.read_excel(
     os.path.join("C:\\Users\\Athul krishna\\myexcels\\","production\\", 'product11.xml.xlsx'),
     engine='openpyxl',
)
df14=pd.read_excel(
     os.path.join("C:\\Users\\Athul krishna\\myexcels\\","production\\", 'product10.xml.xlsx'),
     engine='openpyxl',
)
df15=pd.read_excel(
     os.path.join("C:\\Users\\Athul krishna\\myexcels\\","production\\", 'product09.xml.xlsx'),
     engine='openpyxl',
)
df16=pd.read_excel(
     os.path.join("C:\\Users\\Athul krishna\\myexcels\\","production\\", 'product08.xml.xlsx'),
     engine='openpyxl',
)


#df1=pd.concat([df12,df13,df14,df15,df16])
df1=pd.concat([df12])
df1.head()

production_id  company_id  branch_id  department_id  shed_id  \
0           3625           1          1              1        3   
1           3993           1          1              1        3   
2           4000           1          1              1        3   
3           4181           1          1              1        3   
4           4216           1          1              1        3   

   machinetype_id  machine_id  design_id            date_time  machine_status  \
0               8         103          1  2020-12-01 20:04:35               0   
1               8         102          1  2020-12-01 20:04:31               0   
2               8          88          1  2020-12-01 20:03:29               0   
3               8          85          1  2020-12-01 20:03:20               0   
4               8         107          1  2020-12-01 20:05:02               0   

   ...  powerfactor  kwh  frequency  no_communication  communication_id  \
0  ...            0    0          0                 0                 0   
1  ...            0    0          0                 0                 0   
2  ...            0    0          0                 0                 0   
3  ...            0    0          0                 0                 0   
4  ...            0    0          0                 0                 0   

            created_on  created_by  modified_on  modified_by  phase_no  
0  2020-10-29 18:54:45           8          NaN            8         1  
1  2020-11-10 13:34:23           8          NaN            8         1  
2  2020-11-10 16:33:04           7          NaN            7         1  
3  2020-11-18 14:19:20           8          NaN            8         1  
4  2020-11-19 13:50:08           8          NaN            8         1  

[5 rows x 78 columns]

In [3]:
df1.shape

(1000, 78)

In [4]:
df2=df1.loc[:, ['running_time','first_revolution','second_revolution','ins_rpm']]

In [5]:
df2.head()

running_time  first_revolution  second_revolution     ins_rpm
0           530              7024                 34  795.169811
1         27343            277923               1283  609.859196
2         29805            232915               1418  468.877705
3         30921            331270               2111  642.904030
4         23062            267630               1532  696.246639

In [6]:
df2.shape
df2.isnull().sum()

running_time         0
first_revolution     0
second_revolution    0
ins_rpm              0
dtype: int64

In [7]:
y=df2.first_revolution
y.head()

0      7024
1    277923
2    232915
3    331270
4    267630
Name: first_revolution, dtype: int64

In [8]:
ff=df2.drop('first_revolution',axis='columns')
pp=ff.drop('ins_rpm',axis='columns')
x=pp.drop('second_revolution',axis='columns')
x.head()

running_time
0           530
1         27343
2         29805
3         30921
4         23062

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
l=LinearRegression()
l.fit(x_train,y_train)
#l.score(x_test,y_test)


LinearRegression()

In [11]:
pickle.dump(l,open('model.pkl','wb'))
#model=

In [17]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
cv=ShuffleSplit(n_splits=5,test_size=0.1,random_state=0)
cross_val_score(LinearRegression(),x,y,cv=cv)


array([0.85466826, 0.82444528, 0.78956836, 0.80488186, 0.80902841])

In [16]:
cross_val_score(Lasso(),x,y,cv=cv)

array([0.85466826, 0.82444528, 0.78956836, 0.80488186, 0.80902841])

In [28]:
def predict(rt):
    k=np.zeros(len(x.columns))
    k[0]=rt
    return l.predict([k])[0]
print(predict(20598))

193205.505847921


In [29]:
import glob, os
os.chdir("C:\\Users\\Athul krishna\\myexcels\\production\\")
import openpyxl 
from datetime import datetime

In [30]:
def extract(file,c1,c2,c3):
    wb_obj = openpyxl.load_workbook(file) 
    sheet_obj = wb_obj.active
    l=[]


    for i in range(2,20+1):
        val=predict(float(sheet_obj.cell(row = i, column = c1).value),float(sheet_obj.cell(row = i, column = c2).value))
        print("Actual:",float(sheet_obj.cell(row = i, column = c3).value),"Predicted:",val)
        
    #print(l,co)
    #return [co,ca,cb,cc]
#extract("C:\\Users\\Athul krishna\\myexcels\\product11.xml.xlsx",12,13

In [146]:
for file in glob.glob("*.xlsx"):
    extract(file,11,13,12)

Actual: 140244.0 Predicted: 126535.73337571594
Actual: 108806.0 Predicted: 115886.77601251226
Actual: 5915.0 Predicted: -4885.709475749185
Actual: 0.0 Predicted: -11922.050497296907
Actual: 95760.0 Predicted: 96802.34613702851
Actual: 0.0 Predicted: -11922.050497296907
Actual: 65247.0 Predicted: 71058.42140207338
Actual: 0.0 Predicted: -11922.050497296907
Actual: 93588.0 Predicted: 98848.02807995523
Actual: 0.0 Predicted: -11922.050497296907
Actual: 0.0 Predicted: -11922.050497296907
Actual: 3150.0 Predicted: -6166.001516488611
Actual: 93159.0 Predicted: 109253.1288918838
Actual: 12454.0 Predicted: 4599.510376079146
Actual: 114528.0 Predicted: 125819.84432367585
Actual: 0.0 Predicted: -10011.195986747278
Actual: 0.0 Predicted: -11922.050497296907
Actual: 0.0 Predicted: -11922.050497296907
Actual: 0.0 Predicted: -11922.050497296907
Actual: 0.0 Predicted: -11922.050497296907
Actual: 0.0 Predicted: -11922.050497296907
Actual: 0.0 Predicted: -11922.050497296907
Actual: 0.0 Predicted: -1192

0.8118795020594881

array([0.56126559, 0.60878834, 0.82588422, 0.91665027, 0.71785643])